name: CI/CD Pipeline

on:
  push:
    branches:
      - aws
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Executable Permission for Gradlew
      run: chmod +x ./gradlew

    -  name: Build and Test
       run: ./gradlew build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PW }}
        
    - name: Build and Push Docker Image
      run: |
        docker build -t joelgyunampark/iamcaster:${{ github.sha }} .
        docker push joelgyunampark/iamcaster:${{ github.sha }}

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull joelgyunampark/iamcaster:${{ github.sha }}
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:8080 joelgyunampark/iamcaster:${{ github.sha }}
